version: '3.5'
services:
 web_dev:
  build: .
  ports:
   - "4000:4000"
  volumes:
   - .:/app
  environment:
   - ENV=development
   - PORT=4000
   - DB=mongodb://mongodb:27017
 mongodb:
  image: mongo:latest
  container_name: "mongodb"
  ports:
    - "27017:27017"
  environment:
   - MONGO_DATA_DIR=/usr/data/db
   - MONGO_LOG_DIR=/dev/null
  volumes:
   - ./data/db:/usr/data/db
  command: mongod --smallfiles --logpath=/dev/null # --quiet
 charts:
   image: quay.io/mongodb/charts:v0.12.0
   hostname: charts
   network_mode: "host"
   ports:
    # host:container port mapping. If you want MongoDB Charts to be
    # reachable on a different port on the docker host, change this
    # to <port>:80, e.g. 8888:80.
    - 80:80
    - 443:443
   volumes:
    - keys:/mongodb-charts/volumes/keys
    - logs:/mongodb-charts/volumes/logs
    - db-certs:/mongodb-charts/volumes/db-certs
    - web-certs:/mongodb-charts/volumes/web-certs
   environment:
    # The presence of following 2 environment variables will enable HTTPS on Charts server.
    # All HTTP requests will be redirected to HTTPS as well.
    # To enable HTTPS, upload your certificate and key file to the web-certs volume,
    # uncomment the following lines and replace with the names of your certificate and key file.
    # CHARTS_HTTPS_CERTIFICATE_FILE: charts-https.crt
    # CHARTS_HTTPS_CERTIFICATE_KEY_FILE: charts-https.key

    # This environment variable controls the built-in support widget and
    # metrics collection in MongoDB Charts. To disable both, set the value
    # to "off". The default is "on".
    CHARTS_SUPPORT_WIDGET_AND_METRICS: "on"
    # Directory where you can upload SSL certificates (.pem format) which
    # should be considered trusted self-signed or root certificates when
    # Charts is accessing MongoDB servers with ?ssl=true
    SSL_CERT_DIR: /mongodb-charts/volumes/db-certs

   secrets:
    - charts-mongodb-uri


volumes:
  keys:
  logs:
  db-certs:
  web-certs:

secrets:
  charts-mongodb-uri:
    external: true

networks:
 default:
  name: web_dev
